language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
install:
- npm install
- npm ls || true
- git diff --exit-code
script:
- git reset --hard
- npm run build
- npm run coverage:jasmine
- npm run lint
after_success:
- npm install -g coveralls
- npm run coverage:upload
deploy:
  provider: npm
  skip_cleanup: true
  email: ci@radon.app
  api_key:
    secure: Berw0wpQ778CxFti2w0AWjEnMkXQ7VRqtiP+B0v10h+QHsBCj4CFNRCuB9xQJwvFieSJNkJ/y8ujSx1YY1TRDb62gguaq/Gsd/ns4g5GilryLANn4N+OjyZyKwFADcuSroi6nOnVKRztSYhAF5NHx1Nhah9ftdfedLeopKL66Vg+GgSsCc5NSahi+zvNCwRYMVxiJPgZOUWNTJvi1+vpNn2sDo7bXcdZxMYC8do2ataCgzyN0UHtjC0GlPwmCHR8IHStGVhXm4Z6SU/dnRt64DDjlq9FN+7dJxG4IT43xZJfVSE+um3d/WPG0Uchaau5bP0fnrFfNGMkkgM+FbStVy+VMmr6S5zZqC+nusQkbsg71MCiqDB/kdxqsnX/vSmFdq0LdLI90r441VJZzYYUbKqsA3nv6fj8MZw3ebUj83NJjxERh8Ahdyq+6YQjwpR7zoI4ZX/U7vGAq8a+X17POMlp+MzOORTa7ID8njgK2RyfCr4xvDAX/w67hNzFOTXlh4581yV7WeZKRilGltagxasH/IlUR7h9tRfXNKbx9uw8mZZtke4eFu21RKQ/Vr3aHrZTqsTWbzsLeXSETGBvRXqJCF8E6dVrpeQTu137LvQnmPzfZjWlLfdGED6V9DxcLaoHNXBpzSLK0/6Y8vplVojfWrZsOWOqA7qAK2XGfTQ=
  on:
    tags: true
    repo: RadonApp/radon-extension-build
