language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
install:
- npm install
- npm ls || true
- git diff --exit-code
script:
- git reset --hard
- npm run build
- npm run coverage:jasmine
- npm run lint
after_success:
- npm install -g coveralls
- npm run coverage:upload
deploy:
  provider: npm
  skip_cleanup: true
  email: neapp-ci@me.dgardiner.net
  api_key:
    secure: IYwUK82+R3Ht48sfSHOer7OsjYAYJJ1LdpIgjZcYYNkg3OQ4807yTarn1NYxUwOx+6roP7pUqq3DsxFeWHSh1eD1rMgky1NfKiEzi/QbmrfGX8yhnq5UHs8enStrKGoSuf3YAkWPVwI6wcCIbpM/64zQXAEwf2pqVoHDkw7IYR6RCkhgZCCbBjgtxFlPx775DcS1mQxVr8nH0QZWv0qTd86U3VlLOIYUhto6cL4vFtkn6/8QYDqdL5aQL5ciiMI5ivbmgxYIIjsUBz/6Z3p+ZATjH+cK5LkWaiT8lhQQbijj4vUJBBtWxuYd4CbMZEMaERwi8xFCMtM/QbTYFsEoz5WIcCkoz4JmGey4Qj5tTcnFQ2wPtgnn+TVKp0tGF3+oSbW6V4/JX3sMIKHbS6Aco3yNlSdtiqhXMYcE4hYZJkoQp36JTITtlILKElv+lgNOyyxkvnC30jTeHA76Aam59KrcGy2TiwBPnGV1O76q6ZOyM+yPRFagr6ZsuiDchnwFS1Vq0pZzhV+Gm3Khno/SV6245C59isxfp51ennYD3qZl6XvNC1HpobL6Zk8DMFfyebsC5mtq3+wW4r+lGiMMPd8D5KrKov9biV0iLIm0IgQj8EY8kQWdlS/Vvlg671dvX5U8ZbKUqujMYdTAAnbnZvfsLVejgSgiTxulVpc0+FU=
  on:
    repo: NeApp/neon-extension-build
    tags: true
